# Rio Hondo College Schedule Collector Configuration - Full Fall 2025 Collection with Details

rio_hondo:
  base_url: "https://ssb.riohondo.edu:8443/prodssb"
  
  # Schedule search endpoint
  schedule_endpoint: "pw_pub_sched.p_listthislist"
  
  # Current term configuration
  current_term:
    code: "202570"  # Fall 2025
    name: "Fall 2025"
  
  # List of terms to collect (can be expanded)
  terms:
    - code: "202570"
      name: "Fall 2025"
  
  # Departments to collect - ALL for complete collection
  departments:
    - "ALL"
  
  # Search parameters
  search_params:
    sel_day: "dummy"
    sel_schd: "dummy"
    sel_camp: "%"
    sel_ism: "%"
    sel_sess: "%"
    sel_instr: "%"
    sel_ptrm: "%"
    sel_zero: "N"
    sel_attrib: "%"
    begin_hh: "5"
    begin_mi: "0"
    begin_ap: "a"
    end_hh: "11"
    end_mi: "0"
    end_ap: "p"

# Collection settings
collection:
  # Maximum retries for failed requests
  max_retries: 3
  
  # Timeout for HTTP requests (seconds)
  timeout: 60
  
  # Delay between requests to avoid overwhelming server (seconds)
  request_delay: 2
  
  # User agent for requests
  user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36"
  
  # Whether to validate SSL certificates
  verify_ssl: true
  
  # Detail collection settings
  collect_details: true  # ENABLED for full collection
  detail_delay: 1.5  # 1.5 seconds between detail requests
  detail_batch_size: 100  # Progress update every 100 courses
  detail_max_concurrent: 1  # Sequential to be respectful

# Output settings
output:
  # Directory to store collected data
  data_dir: "data"
  
  # File naming pattern (supports strftime format codes)
  filename_pattern: "schedule_{term_code}_detailed_{timestamp}.json"
  
  # Whether to create a 'latest' symlink
  create_latest_link: true
  
  # Compression (none, gzip, bzip2)
  compression: "gzip"  # Compress due to large size with details

# API Configuration (for future LLM integration)
api:
  # Claude API settings (to be configured when ready)
  anthropic:
    enabled: false
    # api_key: set via ANTHROPIC_API_KEY environment variable
    model: "claude-3-sonnet-20240229"
    max_tokens: 4096
    temperature: 0.0

# Logging settings
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
# Notification settings (optional)
notifications:
  enabled: false
  # webhook_url: set via WEBHOOK_URL environment variable
  on_success: true
  on_failure: true