# Rio Hondo College Schedule Collector Configuration - Small Detail Test

rio_hondo:
  base_url: "https://ssb.riohondo.edu:8443/prodssb"
  
  # Schedule search endpoint
  schedule_endpoint: "pw_pub_sched.p_listthislist"
  
  # Current term configuration
  current_term:
    code: "202570"  # Fall 2025
    name: "Fall 2025"
  
  # Departments - not used for detail collection
  departments:
    - "ACCT"

# Collection settings
collection:
  # Maximum retries for failed requests
  max_retries: 3
  
  # Timeout for HTTP requests (seconds)
  timeout: 60
  
  # Delay between requests to avoid overwhelming server (seconds)
  request_delay: 2
  
  # User agent for requests
  user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36"
  
  # Whether to validate SSL certificates
  verify_ssl: true
  
  # Detail collection settings
  collect_details: true
  detail_delay: 2  # 2 seconds between detail requests
  detail_batch_size: 5  # Small batch for testing
  detail_max_concurrent: 1  # Sequential

# Output settings
output:
  # Directory to store collected data
  data_dir: "data/test"
  
  # File naming pattern (supports strftime format codes)
  filename_pattern: "schedule_{term_code}_detailed_{timestamp}.json"
  
  # Whether to create a 'latest' symlink
  create_latest_link: true
  
  # Compression (none, gzip, bzip2)
  compression: "none"

# Logging settings
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"